### ISSUE TITLE
Why is context required as static in `ExpandedSecretKey::sign_prehashed`

### ISSUE THREAD

**Issue by lovesh** [dalek-cryptography/ed25519-dalek#105]
In `ExpandedSecretKey::sign_prehashed` [here](https://github.com/dalek-cryptography/ed25519-dalek/blob/master/src/secret.rs#L461), the `context` is required as reference to a static? Is it to prevent (to some extent) applications from accidentally using different contexts?

**Comment by isislovecruft** [comment]
Hi @lovesh! There wasn't a particularly good reason, other than trying to avoid requiring allocations, since the ed25519ph algorithm was generally intended/designed for constrained environments which might not be able to handle large message sizes. My assumption was that using a `&[u8]`, rather than a `String`, would likely be fine for those same environments, since (for most use cases, afaik) one generally only needs one context per application, not per signing operation.

Did you have a different use for which this doesn't work?

**Comment by lovesh** [comment]
Hi @isislovecruft, thanks for replying. I was getting started with WASM (so it might just be my ignorance) and wanted to use Dalek's x25519 and ed25519 through WASM. I could not see how I could receive a `context` as bytes make that static so that I can pass a reference to `sign_prehashed`. [Here is my relevant function](https://github.com/lovesh/wasm_25519/blob/master/src/sig_ed25519.rs#L161).

**Comment by nickray** [comment]
Looks like it's no longer static, but the remaining explicit `'a` lifetime is not necessary either.

**Comment by isislovecruft** [comment]
It sounds like this issue is now moot, but feel free to reopen if I've misunderstood.
