### ISSUE TITLE
semver break in 1.0.0-pre.4

### ISSUE THREAD

**Issue by ijackson** [dalek-cryptography/ed25519-dalek#138]
### Steps to reproduce ###

```rustcargo@zealot:~/Rustup/Itself$ git clone https://github.com/rust-lang/rustup rustup3
Cloning into 'rustup3'...
remote: Enumerating objects: 17372, done.        
remote: Total 17372 (delta 0), reused 0 (delta 0), pack-reused 17372        
Receiving objects: 100% (17372/17372), 6.09 MiB | 1.12 MiB/s, done.
Resolving deltas: 100% (11820/11820), done.
rustcargo@zealot:~/Rustup/Itself$ cd rustup3/
rustcargo@zealot:~/Rustup/Itself/rustup3$ cargo build
...
   Compiling ed25519-dalek v1.0.0-pre.3
...
    Finished dev [unoptimized + debuginfo] target(s) in 1m 19s
```

Observe that the build works, and that this is with `1.0.0-pre3`.  Now switch to `1.0.0-pre4`:

```
rustcargo@zealot:~/Rustup/Itself/rustup3$ cargo update -p ed25519-dalek --precise 1.0.0-pre.4
    Updating crates.io index
      Adding ed25519 v1.0.1
    Updating ed25519-dalek v1.0.0-pre.3 -> v1.0.0-pre.4
      Adding signature v1.1.0
rustcargo@zealot:~/Rustup/Itself/rustup3$ cargo build                                        
   Compiling signature v1.1.0
   Compiling rustup v1.22.1 (/volatile/rustcargo/Rustup/Itself/rustup3)
   Compiling ed25519 v1.0.1
   Compiling ed25519-dalek v1.0.0-pre.4
   Compiling pgp v0.5.2
error[E0599]: no function or associated item named `from_bytes` found for struct `ed25519_dalek::Signature` in the current scope
  --> /home/rustcargo/.cargo/registry/src/github.com-1ecc6299db9ec823/pgp-0.5.2/src/crypto/eddsa.rs:58:49
   |
58 |             let sig = ed25519_dalek::Signature::from_bytes(&sig_bytes)?;
   |                                                 ^^^^^^^^^^
   |                                                 |
   |                                                 function or associated item not found in `ed25519_dalek::Signature`
   |                                                 help: there is an associated function with a similar name: `to_bytes`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
           `use ed25519_dalek::ed25519::signature::Signature;`

error[E0599]: no method named `verify` found for struct `ed25519_dalek::PublicKey` in the current scope
  --> /home/rustcargo/.cargo/registry/src/github.com-1ecc6299db9ec823/pgp-0.5.2/src/crypto/eddsa.rs:60:16
   |
60 |             pk.verify(hashed, &sig)?;
   |                ^^^^^^ method not found in `ed25519_dalek::PublicKey`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
           `use ed25519_dalek::Verifier;`

error[E0599]: no method named `sign` found for struct `ed25519_dalek::Keypair` in the current scope
  --> /home/rustcargo/.cargo/registry/src/github.com-1ecc6299db9ec823/pgp-0.5.2/src/crypto/eddsa.rs:83:24
   |
83 |     let signature = kp.sign(digest);
   |                        ^^^^ method not found in `ed25519_dalek::Keypair`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
           `use ed25519_dalek::Signer;`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `pgp`.

To learn more, run the command again with --verbose.
rustcargo@zealot:~/Rustup/Itself/rustup3$ 
```

Sorry for not minimising this further.  I tried producing a repro based only on rpgp, but ran into probably-unrelated trouble.

cc @kinnison

**Comment by burdges** [comment]
Is `cargo update` meant to obey some semver restriction?  

["A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version."](https://semver.org/)

**Comment by kinnison** [comment]
Cargo follows/uses https://github.com/steveklabnik/semver#requirements based on https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

While you are correct that by pure semver rules pre.x/pre.x+1 should be considered not semver-compatible I fear the rules Cargo follows may not obey that.

**Comment by tarcieri** [comment]
There wouldn't be a whole lot of purpose to prereleases if you can't make semver breaking changes. You may as well cut a 1.0 and call it a day.

IMO `-pre` releases are the last chance to make semver breaking changes before cutting a final release.

**Comment by ijackson** [comment]
Tony Arcieri writes ("Re: [dalek-cryptography/ed25519-dalek] semver break in 1.0.0-pre.4 (#138)"):
> There wouldn't be a whole lot of purpose to prereleases if you can't make
> semver breaking changes. You may as well cut a 1.0 and call it a day.
> 
> IMO -pre releases are the last chance to make semver breaking changes before
> cutting a final release.

OK.  Sorry for being confused then.  I had misunderstood the intent of
your version numbering.

I take it from this discussion that this API change was intentional.

In which case please close this issue, and I guess I need to report
this build failure as an issue against [r]gpg.

Thanks,
Ian.

-- 
Ian Jackson <ijackson@chiark.greenend.org.uk>   These opinions are my own.  

Pronouns: they/he.  If I emailed you from @fyvzl.net or @evade.org.uk,
that is a private address which bypasses my fierce spamfilter.

**Comment by kinnison** [comment]
While I agree with the *intent* of marking things `-pre.X` this is not how cargo interprets the versions, and as such it's not ideal for the project to behave like this.  I think if this is going to be a one-off "hiccough" the ecosystem might be able to absorb the shock, but if this kind of thing occurs more widely then it might be really hard for people to know that `cargo update` will at least be compile-safe which is the intent of cargo's behaviour wrt. semantic versioning.

**Comment by burdges** [comment]
Yes, I think cargo itself should obey semver of course, but the `cargo update` docs imply it does whatever you tell it with `--precise`.  

We scrambled an ed25519 upgrade over this too, although I never saw the breakage first hand, so yes maybe there exists a semver handling bug in either `cargo` or `cargo update` without `--precise`, but..

I'm shocked if cargo could even tell that 1.0.0-pre.3 < 1.0.0-pre.4 since that's not actually in the semver rules?  Is 1.0.0-aleph < 1.0.0-bet?  It is in lexicographic ordering and in Israel, but not necessarily anywhere else.

**Comment by kinnison** [comment]
I am not certain how cargo compares the versions exactly though they are defined in the crate I linked in an above comment.
Interestingly https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field uses the phrase "before you reach 1.0.0" so what matters is whether "1.0.0-pre.1" sorts *before* "1.0.0" , and if so, if Cargo correctly treats it as "less than 1.0.0 and thus in the 0.x.y type situation" - though even if it did treat it as a putative "0.99999.0-pre.1" the change to "-pre.2" would probably be considered a patch level change (thus minor level because of the leading zero), and thus semver compatible.

Looking at the semver crate, it does parse the "pre" suffix though it does that as a number of suffixes separated by dots, so you end up with (1,0,0,["pre",3]) - so 1.0.0-pre.3 will compare as smaller than 1.0.0-pre.4 at least.  Ultimately in that crate, the compatibility check we're interested in boils down to https://github.com/steveklabnik/semver/blob/master/src/version_req.rs#L524 where it simply says "pre.4 is compatible with pre.3 if it is greater than or equal to" - i.e. at no point are incrementing prerelease numbers considered semantically breaking changes.

While this is not entirely what https://semver.org/#spec-item-9 seems to state, it is what Cargo does (and presumably always has) do.  The ordering of versions appears to match https://semver.org/#spec-item-11 part 4.  What spec-item-9 states is that a pre-release may not convey the same compatibility as the "normal version" it is a prerelease of.  i.e. if you had released 1.0.0 then 1.0.1-pre.1 *might* be semver-incompatible with 1.0.0 even though 1.0.1 ought to be compatible.  This is not necessarily the same claim as that 1.0.0-pre.4 might be incompatible with 1.0.0-pre.3, however I suppose you're at liberty to interpret the specification like that.  Sadly it's not how the semver crate, and thus Cargo, does.

It's unfortunate that, in order to operate correctly, rpgp ended up depending on `^1.0.0-pre.3` since that opened it up to failing if you made incompatible changes between there and `1.0.0` which you did do.  The nominally correct thing to do is to shrug and say "oh well, rpgp gets to fix itself, silly thing for depending on a prerelease", but perhaps, if you're feeling a little more charitable, then it'd be helpful to see why this particular API change happened (presumably a case of the traits not being exported at the same point as the types and thus not benefiting from overlapping names in quite the same way any longer) and if there's a neat way to correct it without requiring downstream crates to tighten their dependencies and/or change their imports and accept that anything running `cargo update` may break in the meantime.

I don't think there's any single "right" answer to all this.  Long term, perhaps `semver` needs updating to understand that pre versions are effectively 100% incompatible with anything but themselves, though whether that'll be unfortunate for people who use prerelease indicators but follow this deviation from semver-proper is up for debate.

If you close this issue without any action (be it a 1.0.0-pre.5 with the export reinstated, or appropriate PRs filed on the more popular of your downstream crates if needed, or an issue filed on `semver` to try and get this behaviour fixed, or something else I've not even thought up yet) then I think it's an opportunity lost for potentially improving the ecosystem by reducing the surprise people would encounter from a `cargo update` -- Certainly I'd be very upset if I'd encountered this myself when updating `rustup`'s dependencies, hence I thought I should weigh in.

**Comment by tarcieri** [comment]
> The nominally correct thing to do is to shrug and say "oh well, rpgp gets to fix itself, silly thing for depending on a prerelease", but perhaps, if you're feeling a little more charitable, then it'd be helpful to see why this particular API change happened

The change in question is #124, FWIW. By its nature it's a breaking change.

**Comment by kinnison** [comment]
Thank you @tarcieri - So it's unfortunate that in this instance, between two versions considered semver-compatible by Cargo, a deliberately breaking change was made under the impression that the version numbers indicated this was acceptable.

I'd guess therefore that there's not an easy fix for this in ed25519-dalek so we need to think of the other options I suggested.  Is there a preference here for which makes the most sense?

**Comment by burdges** [comment]
I've phrase it this way:  Should cargo recognize 1.0.0-pre.3 < 1.0.0-pre.4 due to the .3 < .4 being considered a patch?  If so, then 1.0.0-pre.4 should've an incomparable name like 1.0.0-pre1.0 or whatever, and either semver or cargo or both should explain this.  If no, then it's a cargo bug.  I'd move this issue to cargo either way because either way at least their documentation requires tweaks.

**Comment by kinnison** [comment]
I've raised this with the cargo team, so hopefully someone there will engage.  I've raised it on the Cargo Zulip here: https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/potential.20semver.20related.20issue
