### ISSUE TITLE
Keypair corrupted after calling to_bytes() and from_bytes() ?

### ISSUE THREAD

**Issue by PaulGrandperrin** [dalek-cryptography/ed25519-dalek#157]
Running this code, I expected to see the exact same outputs, but it's not, the `FieldElemets` of the `EdwardsPoint` do not have the same values.

Maybe it's normal and equivalent in some way, I have no idea how those things work, but it's still surprising.

Doing another round of `to_bytes()` and `from_bytes()` yields the same result as the last one, so at least it becomes stable after some point.

```rust
use ed25519_dalek::Keypair;

fn main() {
    let kp = Keypair::generate(&mut rand::thread_rng());
    println!("{:?}", kp);

    let k = Keypair::from_bytes(&kp.to_bytes()).unwrap();
    println!("{:?}", k);
}
```

outputs

```
Keypair { secret: SecretKey: [0, 173, 75, 175, 56, 209, 147, 101, 16, 11, 220, 110, 206, 94, 113, 43, 117, 159, 102, 178, 104, 135, 73, 223, 23, 28, 137, 42, 98, 91, 24, 245], public: PublicKey(CompressedEdwardsY: [112, 115, 160, 69, 215, 171, 228, 138, 31, 165, 76, 214, 96, 33, 48, 248, 253, 18, 230, 158, 85, 156, 245, 208, 143, 152, 169, 203, 86, 211, 169, 182]), EdwardsPoint{
        X: FieldElement51([1039128021298580, 1134235145357933, 1035743906973319, 138329752640646, 502063388520511]),
        Y: FieldElement51([2219275233526120, 850066345533244, 2008185325197776, 721736418813914, 1778955120259106]),
        Z: FieldElement51([1845178443310108, 1081175563460485, 645888333136340, 274894220718423, 86510465060202]),
        T: FieldElement51([940337176406021, 1417306854816404, 1832059415140659, 764789922519386, 2069098409579660])
}) }
Keypair { secret: SecretKey: [0, 173, 75, 175, 56, 209, 147, 101, 16, 11, 220, 110, 206, 94, 113, 43, 117, 159, 102, 178, 104, 135, 73, 223, 23, 28, 137, 42, 98, 91, 24, 245], public: PublicKey(CompressedEdwardsY: [112, 115, 160, 69, 215, 171, 228, 138, 31, 165, 76, 214, 96, 33, 48, 248, 253, 18, 230, 158, 85, 156, 245, 208, 143, 152, 169, 203, 86, 211, 169, 182]), EdwardsPoint{
        X: FieldElement51([1631760027585913, 1885808940211346, 1103173116524294, 326070052283251, 978756843016459]),
        Y: FieldElement51([1314840981304176, 1155352991363420, 1011876978802821, 1204963725159119, 961648368859801]),
        Z: FieldElement51([1, 0, 0, 0, 0]),
        T: FieldElement51([1529777572342547, 1328769832603867, 1094500934649192, 155887609652086, 1364883280288456])
}) }

```

**Comment by AnomalRoil** [comment]
They are the same, but the `from_bytes` function is relying on the `decompress` function:
https://github.com/dalek-cryptography/ed25519-dalek/blob/925eb9ea56192053c9eb93b9d30d1b9419eee128/src/public.rs#L139-L142
and the `decompress` code fixes the coordinate Z to 1:
https://github.com/dalek-cryptography/curve25519-dalek/blob/3e189820da03cc034f5fa143fc7b2ccb21fffa5e/src/edwards.rs#L190-L206

But this is not a problem, because EdwardsPoint as defined in dalek are in so-called "extended Edwards form", while we are more used to be working using "affine coordinates"... See for more details:
https://en.wikipedia.org/wiki/Edwards_curve#Projective_homogeneous_coordinates

So we can convert these points into affine coordinates and check equality to make sure everything's fine if needed.

In theory we could do so using the following code:
https://github.com/dalek-cryptography/curve25519-dalek/blob/3e189820da03cc034f5fa143fc7b2ccb21fffa5e/src/edwards.rs#L409-L420
But the EdwardsPoint field of the PublicKey struct has a (crate) visibility, making it not easily doable, especially since we don't want to rely on serialization functions that might transform our points in our PoC code.

But it's totally possible to do it manually too:
a FieldElement51 can be turned into a "regular base 10 value" by simply computing:
`value[0]+value[1]*(2^51)+value[2]*(2^102)+value[3]*(2^153)+value[4]*(2^204)`
since it's a really just a base 51 representation of that value.

And so, to check the equality of our two EdwardsPoints in Edwards coordinates, we need to check that `X/Z == X'/Z'` and similarly for Y since **we want to check it in affine coordinate**. (The value T is just a place to store a pre-computed value, we don't need to worry about it.)

But since we hate inverting elements, we prefer multiplying by the other Z value, which in your case is easy since Z' is 1.

So we want to check that:
XZ' == X'Z and YZ' == Y'Z
but Z' = FieldElement51([1, 0, 0, 0, 0]) = 1
So we only have to check that:
`X == X'Z && Y == Y'Z`

So we have:
```
X: FieldElement51([1039128021298580, 1134235145357933, 1035743906973319, 138329752640646, 502063388520511]) 
= 12908556154291066148293639296566491585542554598358961951168623296329834425748
Y: FieldElement51([2219275233526120, 850066345533244, 2008185325197776, 721736418813914, 1778955120259106]) 
= 45738730588378962570394774725791699706188144775725971058559789639520790774120
Z: FieldElement51([1845178443310108, 1081175563460485, 645888333136340, 274894220718423, 86510465060202]) 
= 2224271320508430551666626071603820852852474673812166998245056056403352429596

X': FieldElement51([1631760027585913, 1885808940211346, 1103173116524294, 326070052283251, 978756843016459]) 
= 25164825713951558758703592693789651488167192504483019319294485271133761146233
Y': FieldElement51([1314840981304176, 1155352991363420, 1011876978802821, 1204963725159119, 961648368859801]) 
= 24724949585926681041369128374156901433990949746660221039670391909132829487984
Z': FieldElement51([1, 0, 0, 0, 0]) = 1
```

We can then compute:
```
X'Z = 55973400121135542236618089925040751621030980576362021744057426935709208320135218194956910706347357418622086778622581930851461488191937600882626393111868
Y'Z = 54994996264993512021007306076568805195742049815570012543642510667178193527744339359297563474012410947916717219086603361997693602052086066568339087974464
```

Which, you'll argue aren't anything like X and Y! But that's because **we're working with field elements**, so we need to reduce these modulo our field order `l=2^255-19`:
```
X'Z % l = 12908556154291066148293639296566491585542554598358961951168623296329834425748
Y'Z % l = 45738730588378962570394774725791699706188144775725971058559789639520790774120
```
And as you can see these are exactly the value you have for X and Y! 
So both points are really the same because it checks out that `X == X'Z && Y == Y'Z` is true.

**Comment by isislovecruft** [comment]
Thank you @AnomalRoil for the well thought out and detailed explanation for the differences in the encoded field elements!
