### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by gbaranski** [dalek-cryptography/ed25519-dalek#166]
Hello, I'm quite new to Rust, but I found using your library extremely difficult, first of all `rust-analyzer` doesn't see what methods on struct exists, I've tried to use this library in the way that libp2p-rust does that [here](https://github.com/libp2p/rust-libp2p/blob/master/core/src/identity/ed25519.rs), but it ended up working the same way. Also you show in the documentation to use `extern crate`, https://github.com/dalek-cryptography/ed25519-dalek/blob/925eb9ea56192053c9eb93b9d30d1b9419eee128/src/lib.rs#L59 
while Rust documentation says [no more `extern crate`](https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html#no-more-extern-crate)

**Comment by isislovecruft** [comment]
Hi @gbaranski! I'm sorry to hear that you have found using ed25519-dalek difficult. The issue with rust-analyzer has, I believe, been fixed in #173.

Adding `extern crate [...]` was required pre-2018 edition of Rust. This crate was originally developed in 2016. People who cannot use the 2018 edition of Rust will still need to do `extern crate rand`, and doing so with the newer editions won't break anything.
