### ISSUE TITLE
when add serde features to use serde_json, had one error

### ISSUE THREAD

**Issue by sunhuachuang** [dalek-cryptography/ed25519-dalek#37]
```
...
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.ed25519-dalek]
path = "ed25519-dalek"
version = "^0.8"
features = ["serde"]

```
main.rs
```
extern crate ed25519_dalek;
extern crate rand;
extern crate serde;
extern crate serde_json;
extern crate sha2;

use ed25519_dalek::{Keypair, PublicKey};
use rand::OsRng;
use sha2::Sha512;

fn main() {
    let mut csprng: OsRng = OsRng::new().unwrap();
    let keypair: Keypair = Keypair::generate::<Sha512, _>(&mut csprng);
    let public_key = keypair.public;

    let s = serde_json::to_string(&public_key).unwrap();
    let pk: PublicKey = serde_json::from_str(&s).unwrap();

    println!("{:?}", pk);
}

```

error is
```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/test-ed25519`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: sequence, expected An ed25519 public key as a 32-byte compressed point, as specified in RFC8032", line: 1, column: 1)', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by sunhuachuang** [comment]
```
➜  test-ed25519 (master) ✗ rustup show
rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.30.0-nightly (9395f0af7 2018-09-02)

```
I use either of versions, all has this error

**Comment by sunhuachuang** [comment]
I test when use bincode to serialize, that is ok !

**Comment by hdevalence** [comment]
The root of this problem is in the `curve25519-dalek` Serde code, which expects to serialize and deserialize into byte arrays.  Since the JSON format does not have a way to express byte arrays, `serde_json` writes the byte array as a list of integers. On deserialize, the code gets a list of integers instead of a byte array, and this causes the error you found.

I am not sure what a good solution to this problem is.

**Comment by isislovecruft** [comment]
Hi @sunhuachuang!

I took a look at the [serde_json repo](https://github.com/serde-rs/json) and there is no way to serialize to a non string type. So what it's doing is taking the bytes of the key, e.g. if `public_key` is:

```rust
PublicKey( CompressedEdwardsY( [109, 163, 2, 144, 197, 194, 30, 49, 12, 52, 150, 255, 112, 79, 198, 125, 190, 205, 113, 27, 244, 188, 129, 46, 188, 244, 52, 29, 242, 174, 235, 165] ))
```

then `s` becomes a `String`:

```rust
"[109,163,2,144,197,194,30,49,12,52,150,255,112,79,198,125,190,205,113,27,244,188,129,46,188,244,52,29,242,174,235,165]"
```

Thus when you go to deserialise it with `from_str(&s)`, it is interpreting that `&str` as a literal slice of bytes representing the ASCII/UTF-8 encoding of the literal characters in the above string:

```
[ 91, 49, 48, 57, 44, 49, 54, 51, 44, 50, 44, 49, 52, 52, 44, 49, 57, 55, 44, 49, 57, 52, 44, 51, 48, 44, 52, 57, 44, 49, 50, 44, 53, 50, 44, 49, 53, 48, 44, 50, 53, 53, 44, 49, 49, 50, 44, 55, 57, 44, 49, 57, 56, 44, 49, 50, 53, 44, 49, 57, 48, 44, 50, 48, 53, 44, 49, 49, 51, 44, 50, 55, 44, 50, 52, 52, 44, 49, 56, 56, 44, 49, 50, 57, 44, 52, 54, 44, 49, 56, 56, 44, 50, 52, 52, 44, 53, 50, 44, 50, 57, 44, 50, 52, 50, 44, 49, 55, 52, 44, 50, 51, 53, 44, 49, 54, 53, 93 ]
```
Obviously, this isn't a `PublicKey`, nor can it be safely turned back into one, since `ed25519-dalek` can't take any byte slice that's variably longer than 32 bytes and try to decode the bytes back into a `String` and then try to parse 8-bit integers back out of them.

Perhaps you can get serde_json to do something smarter than turning everything into a `String` somehow? Their [docs also mention](https://docs.serde.rs/serde_json/ser/fn.to_string.html) that most of their serialisation methods will fail if the original data is a non-string. Or maybe use a different serialisation library if possible?

**Comment by sunhuachuang** [comment]
Thank you very much, I decide use` bincode` to do the serialize. work well.
