### ISSUE TITLE
PartialOrd and Ord for keys

### ISSUE THREAD

**Issue by AljoschaMeyer** [dalek-cryptography/ed25519-dalek#52]
Hi,

is there any reason why the key types don't implement `PartialOrd` and `Ord`? I guess you might want to avoid comparisons of secret keys, but at least `PublicKey` could simply derive it (or perhaps do a constant-time comparison).

The same applies for the `Hash` trait.

**Comment by isislovecruft** [comment]
Hi @AljoschaMeyer!

Yes, you're correct that we don't want to make comparisons between secret keys. There's functionality in the `subtle` crate for comparing the equality of two equally-sized byte arrays in constant time, if you need to check if two secret keys are the same. Comparing secret keys by their sort-ordering would be dangerous without using a constant time sorting network, which would be relatively expensive and I'm also not sure why anyone would ever need to do this.

For public keys (after #61 is merged), there isn't a way to do these types of comparisons (or `Hash`, because for `Hash` iff `pk1 == pk2` then `hash(pk1)` must equal `hash(pk2)`) because the finite field elements used for the internal coordinates in the various elliptic curve point formats contain what are called "limbs" which for this field store either an alternation of 25- and 26- bit values (for 32-bit architectures) or 51-bit values (for 64-bit architectures). The extra bits are used internally to prevent overflow, and occasionally need to be rebalanced and reduced modulo the field order. As a simple example, working in `GF(5) = {0,1,2,3,4}`, if (in my representation) I allowed something to grow to "8" it would obviously not equal `3`, however after a reduction it would, since `8 (mod 5) = 3`. (Hopefully it's clearer now why it doesn't make sense to implement `Hash`?) So implementing this would then require either than elements are reduced at all times (which is slow and costly) or doing the reduction as the first part of the comparison, however we then run into the issue that "sort order" doesn't really make any sense for a 4-coordinate object in a projective space.

**Comment by cyphar** [comment]
I'm not sure I understand why `Hash` cannot be implemented because of the internal representation. Why not just implement it by doing `Hash(PublicKey::to_bytes)`. Yes, the current implementation of `PartialEq` is `#[derive]`d but that's something which can surely be changed to also do a comparison of `PublicKey::to_bytes`. Is there any circumstance where it would be incorrect to say that semantically `pk1 == pk2` iff `pk1.to_bytes() == pk2.to_bytes()`?

I hit this issue (and #120) because I'm trying to put a `PublicKey` (or rather, a tuple which contains a `PublicKey`) inside a `HashMap` and that isn't possible because `Hash` isn't implemented for `PublicKey`) so I need to define a wrapping structure to work around this.

**Comment by burdges** [comment]
There are both compressed and projective coordinates now, so you can safely do
```
impl Hash for PublicKey {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.as_bytes().hash(state);
    }
}
```

**Comment by davidrusu** [comment]
@burdges @isislovecruft given what you say about safe, normalized forms of a public key using `as_bytes`. How is the appetite for an `impl Hash for PublicKey` and perhaps an `impl Ord for PublicKey`.

The use-case is as described in the opening post, public keys are natural to use as keys into a Map, or in as members of a Set, and hence require either an Ord or Hash impl.
