### ISSUE TITLE
Public Key recovery

### ISSUE THREAD

**Issue by NN-Binary** [dalek-cryptography/ed25519-dalek#88]
Hi,

I'm having a hard time recovering public keys from a Signature in this crate.
How is it done? Anyone have a proper example? Thank you.

**Comment by burdges** [comment]
If you mean like the ecrecover used by ethereum for ecdsa keys, then you need a more malleable schnorr signatures for that, but doing so makes HDKD insecure.  If you do anything "blockchain" then your users will do HDKD whether you want them to or not, so just forget about ecrecover.  In fact ecrecover is a really dumb idea anyways because it breaks batch verification.

**Comment by james-darkfox** [comment]
@NN-Binary Why do you want public key recovery from the signature? Are you trying to reduce the storage costs of many `(public key, message, signature)` triples?

@burdges What do you mean by 'more malleable' being necessary for public key recovery? Ed25519 is already malleable due to the cofactor.

Schnorr has two variations; supporting exclusively either public key recovery or batched verification under a common signer.

**Ed25519, as an official specification, forces the decision to the latter.** A Ristretto255 Schnorr implementation can decide either without worrying about the cofactor/malleability of Ed25519.

HDKD only blinds the keypair; where the blinding factor is public in the weak case. The issue is when cofactor-many public keys are equivalent yet indistinguishable to a human. An inconsistency between user expectation and reality, but is this an security-level issue?

**Comment by james-darkfox** [comment]
@burdges Likely cause for confusion. Ethereum's ecrecover isn't using Schnorr, rather it uses ECDSA over secp256k1 - which is a prime order group, thus not malleable but slower than Ristretto255.

**Comment by burdges** [comment]
@james-darkfox  Cofactors are irrelevant here.

You cannot do public key recovery if you define c = H(R,msg,pk) of course.  You must increase malleablity by defining c = H(R,msg) if you want public key recovery.

There are niche cases where c = H(R,msg) gets used securely, like deep inside some zero knowledge proofs, and the security proofs cover that form, but..

You cannot claim security for any general pupose signature scheme that uses c = H(R,msg) because the signature scheme's security is not composable in ways everyone expects.  If you want HDKD and ecRecover then you must use ECDSA, not Schnorr.

In HDKD there are many secret keys x and y for which x = z y for some publicly known z = H(foo)/H(bar).  As a result, you can transform a signature with c = H(R,msg) for x into a signature for y.  It's not only cyber-coins using HDKD  since projects like GNS and Tor hidden services do so too.  Ristretto cannot improve the situations because cofactors have nothing whatsoever to do with the problem.  

See:  https://www.deadalnix.me/2017/02/17/schnorr-signatures-for-not-so-dummies/

**Comment by james-darkfox** [comment]
@burdges Thanks for the link and correcting me. It seems I conflated ed25519's selection for one Schnorr representation with hashed inclusion of the public key.

**Comment by burdges** [comment]
There are similar issues with using BLS for cyber-coin accounts for the same reason:  Yes, you can make BLS non-malleable, but then you've killed most of BLS' advantages. 

As an aside, we should expect some risky, or outright insecure, combinations of the form ECDSA + ecRecover + HDKD + multisignature + adaptor-like signature + etc too, but for which pairwise nobody knows attacks.. and maybe deployed among the army of poorly designed non-private layer 2 solutions.
